title = "gitleaks config"

[[rules]]
description = "Supabase API Key"
regex = '''(sbp_[a-f0-9]{48})'''

[[rules]]
description = "Generic API Key"
regex = '''(?i)(api|key|token|secret|password)[^a-zA-Z0-9][a-zA-Z0-9_\-]{20,}'''

[allowlist]
files = [
  "^config.example.js$",
  "^.env.example$"
]