-- CREATE OR REPLACE FUNCTION delete_if_read()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   IF NEW.is_read = TRUE THEN
--     DELETE FROM notes WHERE id = NEW.id;
--     RETURN NULL; -- Prevents the update from completing
--   END IF;
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE OR REPLACE FUNCTION delete_expired_notes()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   IF current_timestamp > TIMESTAMP WITH TIME ZONE '2025-09-11 18:28:49.76+00'
--      OR (NEW.expires_at IS NOT NULL AND current_timestamp > NEW.expires_at) THEN
--     DELETE FROM notes WHERE id = NEW.id;
--     RETURN NULL;
--   END IF;
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE TRIGGER trigger_delete_if_read
-- BEFORE UPDATE ON notes
-- FOR EACH ROW
-- EXECUTE FUNCTION delete_if_read();

-- CREATE TRIGGER trigger_delete_expired_notes
-- BEFORE UPDATE ON notes
-- FOR EACH ROW
-- EXECUTE FUNCTION delete_expired_notes();